Базовая стилизация
htmlacademy-htmlcss/1543677-sedona-1 pull request #4
Opened 2024-02-05 10:33 UTC by MeirbekAshirbayev

2024-02-06 09:23 UTC, aimenin requested changes
Мне нравится работа!
Парочка замечаний оставил.
Так же вопрос по шрифтам, подключились, все норм?
Просто там в url, насколько я помню, тоже путь в кавычки нужно взять

```css
@font-face {
  font-family: "PT Sans";
  font-weight: 400;
  font-style: normal;
  src: url("../fonts/ptsans-400.woff2") format("woff2");
  font-display: swap;
}
```

Вот так

2024-02-06 09:23 UTC, aimenin commented on styles/styles.css
> +  background-image: url(../images/subscribe.png);
если не ошибаюсь, что заработало нужно взять изображение в кавычки
```suggestion
  background-image: url("../images/subscribe.png");
```

2024-02-06 09:23 UTC, aimenin commented on styles/styles.css
> +  background-image: url(../images/catalog-hiro.png);
когда указываем background-image так же указываем background-color, чтобы если у нас не загрузился image, у нас остался какой то фон.
Лучше подбирать похожий цвет фона на цвет изображения.

2024-02-06 10:11 UTC, MeirbekAshirbayev commented on styles/styles.css
> +  background-image: url(../images/catalog-hiro.png);
Здесь задний фон находится у двух секшонов, у одной буквы свет белый а второй черный какой фон выбрать

2024-02-06 10:12 UTC, MeirbekAshirbayev commented on styles/styles.css
> +  background-image: url(../images/subscribe.png);
без кавычек тоже работает

2024-02-08 13:54 UTC, aimenin approved these changes
👍

2024-02-08 13:54 UTC, merged